import {
  AlertTriangle,
  ArrowLeft,
  Award,
  Bird,
  Building2,
  Calendar,
  Check,
  Castle,
  Crown,
  Flame,
  Globe,
  Home,
  Keyboard,
  Landmark,
  Lock,
  LogIn,
  LogOut,
  Map,
  Medal,
  Mountain,
  PartyPopper,
  PenLine,
  Play,
  Puzzle,
  RefreshCw,
  Repeat,
  Share2,
  Snowflake,
  Sprout,
  Star,
  Sun,
  Target,
  Timer,
  Trash2,
  TreePalm,
  Trophy,
  Settings,
  UserRound,
  Users,
  Volume2,
  VolumeX,
  X,
  Zap,
} from 'lucide-react';

const ICONS = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  award: Award,
  bird: Bird,
  building2: Building2,
  calendar: Calendar,
  castle: Castle,
  check: Check,
  crown: Crown,
  flame: Flame,
  globe: Globe,
  home: Home,
  keyboard: Keyboard,
  landmark: Landmark,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  map: Map,
  medal: Medal,
  mountain: Mountain,
  party: PartyPopper,
  pencil: PenLine,
  play: Play,
  puzzle: Puzzle,
  refresh: RefreshCw,
  repeat: Repeat,
  share: Share2,
  snowflake: Snowflake,
  sprout: Sprout,
  settings: Settings,
  star: Star,
  sun: Sun,
  target: Target,
  timer: Timer,
  trash: Trash2,
  treepalm: TreePalm,
  trophy: Trophy,
  user: UserRound,
  users: Users,
  volume2: Volume2,
  volumeX: VolumeX,
  x: X,
  zap: Zap,
};

export default function Icon({ name, size = 18, strokeWidth = 2, ...rest }) {
  const Cmp = ICONS[name] || Star;
  return <Cmp size={size} strokeWidth={strokeWidth} {...rest} />;
}
